### PR TITLE
Makes init containers respect security context.

### PR DESCRIPTION
**Pull request by KarolisKundrotas-Hostinger**
- Makes init containers respect security context.

### CODE REVIEW

**Comment by PabloHiro** [comment]
@miraai @camattin , is there anything missing in this PR apart from the `artifacthub.io/changes` in the Chart.yaml file?

If not, I can work on that based on the missing info. 

This is a show stopper in our case as well.

**Comment by miraai** [comment]
> @miraai @camattin , is there anything missing in this PR apart from the `artifacthub.io/changes` in the Chart.yaml file?
> 
> If not, I can work on that based on the missing info.
> 
> This is a show stopper in our case as well.

As far as I am concerned, this is okay, lets just wait for @camattin to take a look. I'll add him as a reviewer as well.

**Comment by camattin** [comment]
LGTM!

**Comment by KarolisKundrotas-Hostinger** [comment]
A little background for this PR:
We at @Hostinger deployed this chart and ended up overriding the template part just to make init container respect security context, as we do not run containers as root. Eventually, we moved to the custom init container, so fixing this became irrelevant. I can update this PR to adhere to your requirements to help others trying to use Rasa charts.

**Comment by miraai** [comment]
> A little background for this PR: We at @hostinger deployed this chart and ended up overriding the template part just to make init container respect security context, as we do not run containers as root. Eventually, we moved to the custom init container, so fixing this became irrelevant. I can update this PR to adhere to your requirements to help others trying to use Rasa charts.

Im glad you found a way that works for you! We are also working on the new helm charts and i am hoping it will resolve most of the issues you were facing. Im also looking forward to your feedback when it gets released!

With that in mind, we can close the PR if this is not needed for you anymore.

Thank you!

**Pull request closed without merging**
